spring.application.name=SpringPractice



# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/coursesdb
spring.datasource.username=${DB_USERNAME:zaka}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=update

# Swagger Config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
