spring.application.name=jdbc


# === PostgreSQL JDBC Config ===
spring.datasource.url=jdbc:postgresql://localhost:5432/coursesdb
spring.datasource.username=${DB_USERNAME:zaka}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=none
